
version: 2

models:
  - name: n225_summary
    description: ""
    columns:
      - name: date
        data_type: date
        description: ""

      - name: ticker
        data_type: int64
        description: ""

      - name: company
        data_type: string
        description: ""

      - name: open
        data_type: float64
        description: ""

      - name: close
        data_type: float64
        description: ""

      - name: high
        data_type: float64
        description: ""

      - name: low
        data_type: float64
        description: ""

      - name: year_high
        data_type: float64
        description: ""

      - name: year_low
        data_type: float64
        description: ""

      - name: volume
        data_type: int64
        description: ""

      - name: avg_vol_30d
        data_type: float64
        description: ""

      - name: prev_close
        data_type: float64
        description: ""

      - name: pct_change
        data_type: float64
        description: ""

      - name: mkt_cap
        data_type: float64
        description: ""

  - name: n225_added_prev_close
    description: ""
    columns:
      - name: date
        data_type: date
        description: ""

      - name: open
        data_type: float64
        description: ""

      - name: high
        data_type: float64
        description: ""

      - name: low
        data_type: float64
        description: ""

      - name: close
        data_type: float64
        description: ""

      - name: adj_close
        data_type: float64
        description: ""

      - name: volume
        data_type: int64
        description: ""

      - name: ticker
        data_type: int64
        description: ""

      - name: prev_close
        data_type: float64
        description: ""

      - name: close_change
        data_type: float64
        description: ""

      - name: avg_vol_30d
        data_type: float64
        description: ""
